# Taskfile.yml - Automation for the Rapid Prototyping System (Using Poetry for Backend)
# Usage: task <task-name>
# Install: https://taskfile.dev/installation/

version: "3"

vars:
  # Define filters for Turborepo commands
  FILTER_FRONTEND: "--filter=frontend"
  FILTER_BACKEND: "--filter=backend"
  FILTER_ALL_APPS: "--filter=frontend --filter=backend..." # Include any future apps
  FILTER_ALL: "" # Target all packages and apps

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list-all

  install:
    desc: "Install all JS dependencies and backend Python dependencies"
    # Changed: Now runs pnpm install AND poetry install
    cmds:
      - echo "Installing frontend/monorepo JS dependencies..."
      - pnpm install
      - echo "Installing backend Python dependencies..."
      - task: install:backend
    # Method to check if installation is needed (basic check for root node_modules AND backend venv)
    # Status check might need refinement based on how poetry manages venvs (e.g., checking for .venv dir)
    # status:
    #   - test -d node_modules
    #   - test -d apps/backend/.venv # Or path if poetry config changes venv location

  install:backend:
    desc: "Install backend Python dependencies using Poetry"
    dir: apps/backend
    cmds:
      - poetry install --sync

  # --- Development ---
  dev:
    desc: "Run frontend and backend development servers concurrently"
    cmds:
      - pnpm turbo run dev {{.FILTER_ALL_APPS}} --parallel --no-cache

  dev:frontend:
    desc: "Run frontend (Next.js) development server"
    dir: apps/frontend
    cmds:
      - pnpm dev

  dev:backend:
    desc: "Run backend (FastAPI) development server using uvicorn (Poetry)"
    dir: apps/backend
    deps: [install:backend] # Ensure dependencies are installed
    cmds:
      # poetry run executes the command within the project's virtual environment
      - "poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000" # Adjust port if needed

  # --- Linting & Formatting ---
  lint:
    desc: "Lint all code in the monorepo using Turborepo"
    cmds:
      - pnpm turbo run lint {{.FILTER_ALL}}
      - task: lint:frontend
      - task: lint:backend

  lint:frontend:
    desc: "Lint frontend code using ESLint"
    dir: apps/frontend
    cmds:
      - pnpm lint

  lint:backend:
    desc: "Lint backend code using Ruff and Black (Poetry)"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run ruff check .
      - poetry run black --check .

  format:
    desc: "Format all code in the monorepo (using prettier, black)"
    cmds:
      - pnpm prettier --write .
      - task: format:backend

  format:backend:
    desc: "Format backend Python code using Black (Poetry)"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run black .

  # --- Type Checking ---
  typecheck:
    desc: "Type check all code (TypeScript, Python)"
    cmds:
      - pnpm --filter frontend run typecheck
      - task: typecheck:backend

  typecheck:frontend:
    desc: "Type check frontend code with TypeScript"
    dir: apps/frontend
    cmds:
      - pnpm tsc --noEmit

  typecheck:backend:
    desc: "Type check backend Python code with mypy (Poetry)"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run mypy .

  # --- Building ---
  build:
    desc: "Build all apps for production using Turborepo"
    deps: [install]
    cmds:
      - pnpm turbo run build {{.FILTER_ALL}}
      - task: build:backend

  build:frontend:
    desc: "Build frontend app for production"
    deps: [install] # Root install should cover frontend deps
    cmds:
      - pnpm turbo run build {{.FILTER_FRONTEND}}

  build:backend:
    desc: "Build backend (placeholder - type check, test as pre-deploy checks)"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - echo "No explicit build step for backend (deployment uses Dockerfile)."
      - echo "Running pre-checks (lint, typecheck)..."
      - task: lint:backend
      - task: typecheck:backend

      - poetry run mypy .

  # --- Testing ---
  test:backend:
    # Task now uses the 'test' script from pyproject.toml
    desc: "Run all backend tests via Poetry script"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run pytest -v tests/

  test:backend:unit:
    desc: "Run backend unit tests only via Poetry script"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run pytest -v tests/unit/

  test:backend:integration:
    desc: "Run backend integration tests only via Poetry script"
    dir: apps/backend
    deps: [install:backend]
    cmds:
      - poetry run pytest -v tests/integration/

  test:frontend:
    # Task now uses the 'test' script from package.json
    desc: "Run frontend unit/integration tests (Jest) via pnpm script"
    dir: apps/frontend
    # Depends on root install which handles frontend deps
    deps: [install]
    cmds:
      - pnpm test

  test:frontend:e2e:
    # Task now uses the 'test:e2e' script from package.json
    desc: "Run frontend E2E tests (Playwright) via pnpm script"
    dir: apps/frontend
    # Depends on root install
    deps: [install]
    cmds:
      - pnpm test:e2e

  # Main test task - runs backend tests and frontend unit/integration tests
  test:
    desc: "Run backend tests and frontend unit/integration tests"
    deps: [install] # Ensure everything is installed
    cmds:
      - echo "Running backend tests..."
      - task: test:backend
      - echo "Running frontend unit/integration tests..."
      - task: test:frontend

  # --- Database ---
  db:seed:
    desc: "Run database seeding script (IMPLEMENT SCRIPT FIRST) (Poetry)"
    dir: apps/backend # Or wherever your seed script lives
    deps: [install:backend]
    cmds:
      # Example: assumes you have a seed.py script in ./scripts
      - echo "Running DB seed script..."
      - poetry run python scripts/seed_db.py # Adjust path as needed
    preconditions:
      - sh: "[ -f scripts/seed_db.py ]" # Check if seed script exists
        msg: "Database seed script not found at scripts/seed_db.py"

  # --- Cleaning ---
  clean:
    desc: "Remove node_modules, build artifacts, and caches"
    cmds:
      - pnpm --recursive exec -- rm -rf node_modules
      - rm -rf node_modules
      - pnpm turbo run clean # Relies on 'clean' scripts in package.json (e.g., rm -rf .next dist build)
      - find . -name '__pycache__' -type d -exec rm -r {} +
      - find . -name '.pytest_cache' -type d -exec rm -r {} +
      - find . -name '.mypy_cache' -type d -exec rm -r {} +
      - rm -rf .turbo
      # Remove Poetry virtual environment if it's created within the project dir
      - if [ -d "apps/backend/.venv" ]; then rm -rf apps/backend/.venv; fi
